// ── P-008-fix5 · SUB_NICHES structured data ──
// Extracted from app/audit/page.legacy.tsx (original dark-theme form)
// Used in:
//   - app/audit/page.tsx  → conditional sub-niche chip grid in Step 1
//   - lib/analysis/recommendations.ts → SUBNICHE_PRODUCT[subNiche] lookup
//   - lib/ai/prompts.ts   → subNiche in Claude prompt context

export const SUB_NICHES: Record<string, Array<{ value: string; label: string; desc: string }>> = {
  lifestyle: [
    { value: 'daily_vlog',    label: 'Vlog ชีวิตประจำวัน',           desc: 'ชีวิต กิจวัตร เดลี่' },
    { value: 'home_deco',     label: 'แต่งบ้าน / Minimalism',        desc: 'ตกแต่งพื้นที่ จัดบ้าน' },
    { value: 'productivity',  label: 'Productivity / พัฒนาตัวเอง',   desc: 'ระบบชีวิต นิสัยดี' },
    { value: 'fashion',       label: 'แฟชั่น / การแต่งตัว',          desc: 'Outfit OOTD สไตล์' },
    { value: 'relationship',  label: 'ความสัมพันธ์ / ครอบครัว',      desc: 'คู่รัก ครอบครัว' },
    { value: 'lifestyle_other', label: 'ไลฟ์สไตล์อื่นๆ',             desc: 'ไม่มีใน list' },
  ],
  education: [
    { value: 'language',          label: 'สอนภาษา',                  desc: 'อังกฤษ ญี่ปุ่น จีน ฯลฯ' },
    { value: 'coding_tech',       label: 'Coding / Tech',             desc: 'โปรแกรม AI เทคโนโลยี' },
    { value: 'career_skill',      label: 'ทักษะอาชีพ',               desc: 'ทำงาน ทักษะมืออาชีพ' },
    { value: 'exam_prep',         label: 'ติว / เตรียมสอบ',           desc: 'GAT PAT TOEIC สอบต่างๆ' },
    { value: 'general_knowledge', label: 'ความรู้ทั่วไป / สาระ',      desc: 'วิทยาศาสตร์ ประวัติ ฯลฯ' },
    { value: 'education_other',   label: 'การศึกษาอื่นๆ',             desc: 'ไม่มีใน list' },
  ],
  finance: [
    { value: 'stock_invest',  label: 'หุ้น / กองทุน',                 desc: 'ลงทุนในตลาด SET กองทุน' },
    { value: 'crypto',        label: 'Crypto / DeFi',                  desc: 'Bitcoin Ethereum Web3' },
    { value: 'saving',        label: 'ออมเงิน / วางแผนการเงิน',       desc: 'งบ ออม FIRE' },
    { value: 'credit_bank',   label: 'รีวิวบัตรเครดิต / ธนาคาร',     desc: 'บัตรเครดิต สิทธิประโยชน์' },
    { value: 'side_income',   label: 'สร้างรายได้เสริม',              desc: 'งาน part-time freelance online' },
    { value: 'finance_other', label: 'การเงินอื่นๆ',                   desc: 'ไม่มีใน list' },
  ],
  beauty: [
    { value: 'makeup_tutorial', label: 'สอนแต่งหน้า',                 desc: 'Tutorial look step-by-step' },
    { value: 'skincare',        label: 'Skincare / รีวิวสกินแคร์',    desc: 'routine ครีม เซรั่ม' },
    { value: 'beauty_review',   label: 'รีวิวสินค้าความงาม',          desc: 'haul รีวิวรวม ซื้อของ' },
    { value: 'haircare',        label: 'เส้นผม / Hair care',           desc: 'ทรงผม ดูแลผม' },
    { value: 'nail',            label: 'เล็บ / Nail art',              desc: 'ทาเล็บ ออกแบบเล็บ' },
    { value: 'beauty_other',    label: 'ความงามอื่นๆ',                 desc: 'ไม่มีใน list' },
  ],
  fitness: [
    { value: 'workout',       label: 'Workout / ออกกำลังกาย',         desc: 'ท่าออกกำลัง gym home workout' },
    { value: 'yoga_pilates',  label: 'Yoga / Pilates',                 desc: 'ยืดเหยียด mindful' },
    { value: 'nutrition',     label: 'โภชนาการ / อาหารสุขภาพ',       desc: 'clean eating แคลอรี่ diet' },
    { value: 'running_sport', label: 'วิ่ง / กีฬา',                   desc: 'วิ่ง ปั่นจักรยาน กีฬา' },
    { value: 'mental_health', label: 'Mental health / สุขภาพจิต',     desc: 'stress จิตใจ mindfulness' },
    { value: 'fitness_other', label: 'สุขภาพอื่นๆ',                   desc: 'ไม่มีใน list' },
  ],
  business: [
    { value: 'startup_sme',      label: 'เริ่มต้นธุรกิจ / SME',       desc: 'เปิดร้าน ธุรกิจใหม่' },
    { value: 'marketing_social', label: 'Marketing / Social Media',    desc: 'โฆษณา content strategy' },
    { value: 'freelance',        label: 'Freelance / WFH',             desc: 'งานฟรีแลนซ์ remote work' },
    { value: 'ecommerce',        label: 'E-commerce / ขายออนไลน์',    desc: 'Shopee Lazada TikTok Shop' },
    { value: 'career',           label: 'Career / สมัครงาน',           desc: 'resume interview พัฒนาอาชีพ' },
    { value: 'business_other',   label: 'ธุรกิจอื่นๆ',                 desc: 'ไม่มีใน list' },
  ],
  food: [
    { value: 'eating_mukbang',    label: 'กินรีวิว / Mukbang',         desc: 'นั่งกิน ลองกิน กินเล่น' },
    { value: 'restaurant_review', label: 'รีวิวร้านอาหาร',             desc: 'แนะนำร้าน ออกไปกิน' },
    { value: 'cooking_tutorial',  label: 'สอนทำอาหาร / สูตร',         desc: 'สูตร ขั้นตอนทำอาหาร' },
    { value: 'healthy_food',      label: 'อาหารสุขภาพ / คลีน',        desc: 'clean food สุขภาพ diet' },
    { value: 'street_food',       label: 'สตรีทฟู้ด / ของกิน',        desc: 'ของกินแปลก ตลาด street' },
    { value: 'food_other',        label: 'อาหารอื่นๆ',                  desc: 'ไม่มีใน list' },
  ],
  travel: [
    { value: 'domestic_travel',      label: 'ท่องเที่ยวในไทย',           desc: 'จังหวัด ที่เที่ยวไทย' },
    { value: 'international_travel', label: 'ท่องเที่ยวต่างประเทศ',     desc: 'เที่ยวนอก ประเทศต่างๆ' },
    { value: 'budget_travel',        label: 'Budget travel / ประหยัด',   desc: 'เที่ยวถูก backpack' },
    { value: 'luxury_travel',        label: 'Luxury travel',             desc: 'โรงแรมหรู business class' },
    { value: 'solo_travel',          label: 'Solo travel / เดี่ยว',      desc: 'เที่ยวคนเดียว ผู้หญิงเดินทาง' },
    { value: 'travel_other',         label: 'ท่องเที่ยวอื่นๆ',           desc: 'ไม่มีใน list' },
  ],
  entertainment: [
    { value: 'comedy',             label: 'ตลก / Comedy',               desc: 'สเก็ตช์ ตลก ขำขัน' },
    { value: 'reaction',           label: 'รีแอค / Commentary',         desc: 'react video comment' },
    { value: 'gaming',             label: 'เกม / Gaming',               desc: 'เล่นเกม review เกม' },
    { value: 'music',              label: 'ดนตรี / ร้องเพลง',           desc: 'cover ร้องเพลง ดนตรี' },
    { value: 'movie_series',       label: 'รีวิวหนัง / ซีรีส์',         desc: 'วิจารณ์ recap เนื้อเรื่อง' },
    { value: 'entertainment_other', label: 'ความบันเทิงอื่นๆ',          desc: 'ไม่มีใน list' },
  ],
  mom_baby: [
    { value: 'newborn',       label: 'ทารก / แรกเกิด 0-1 ปี',         desc: 'ของใช้เด็กแรกเกิด นม ผ้าอ้อม' },
    { value: 'toddler',       label: 'เด็กเล็ก 1-5 ปี',               desc: 'ของเล่น พัฒนาการ เสื้อผ้าเด็ก' },
    { value: 'parenting_tips', label: 'เลี้ยงลูก / Parenting tips',    desc: 'เทคนิคเลี้ยงลูก พัฒนาการ' },
    { value: 'maternity',     label: 'คุณแม่ตั้งครรภ์ / Maternity',   desc: 'ของใช้แม่ท้อง prenatal' },
    { value: 'breastfeeding', label: 'นมแม่ / Breastfeeding',          desc: 'เครื่องปั๊มนม อุปกรณ์ให้นม' },
    { value: 'kids_edu',      label: 'การศึกษาเด็ก / ของเล่นเสริม',   desc: 'ของเล่น educational toy' },
    { value: 'mom_baby_other', label: 'แม่และเด็กอื่นๆ',               desc: 'ไม่มีใน list' },
  ],
  gaming: [
    { value: 'mobile_gaming', label: 'มือถือ / Mobile Gaming',         desc: 'ROV PUBG Free Fire Genshin' },
    { value: 'pc_gaming',     label: 'PC / Console Gaming',             desc: 'PC Steam PS5 Xbox' },
    { value: 'game_review',   label: 'รีวิวเกม / Game Review',         desc: 'แนะนำเกมใหม่ รีวิว' },
    { value: 'gaming_setup',  label: 'Gaming Setup / อุปกรณ์',         desc: 'peripherals setup desk tour' },
    { value: 'esports',       label: 'E-sports / การแข่งขัน',          desc: 'ทัวร์นาเมนต์ pro scene' },
    { value: 'gaming_other',  label: 'เกมอื่นๆ',                       desc: 'ไม่มีใน list' },
  ],
  cafe: [
    { value: 'cafe_review',  label: 'รีวิวคาเฟ่',                     desc: 'แนะนำคาเฟ่สวย บรรยากาศดี' },
    { value: 'coffee_brew',  label: 'ชงกาแฟ / Specialty Coffee',       desc: 'Pour Over V60 Aeropress' },
    { value: 'bubble_tea',   label: 'บับเบิ้ลที / ชานมไข่มุก',        desc: 'รีวิว ทำเอง ลองสูตร' },
    { value: 'home_cafe',    label: 'Home Cafe / ทำเครื่องดื่มที่บ้าน', desc: 'ทำกาแฟ ชาเอง สูตร' },
    { value: 'bakery_cafe',  label: 'เบเกอรี่ / ขนม',                  desc: 'เบเกอรี่ ขนมคาเฟ่ ทำขนม' },
    { value: 'cafe_other',   label: 'คาเฟ่อื่นๆ',                      desc: 'ไม่มีใน list' },
  ],
  health: [
    { value: 'supplement',         label: 'อาหารเสริม / Supplement',   desc: 'วิตามิน โปรตีน คอลลาเจน' },
    { value: 'traditional_medicine', label: 'แพทย์แผนไทย / สมุนไพร', desc: 'ยาสมุนไพร นวด ไทย' },
    { value: 'mental_wellness',    label: 'สุขภาพจิต / Mindfulness',   desc: 'meditation สติ ลดเครียด' },
    { value: 'medical_device',     label: 'เครื่องมือแพทย์ / อุปกรณ์', desc: 'เครื่องวัดความดัน น้ำตาล' },
    { value: 'skin_health',        label: 'โรคผิวหนัง / สุขภาพผิว',   desc: 'สิว ผด ผื่น แพ้' },
    { value: 'health_other',       label: 'สุขภาพอื่นๆ',               desc: 'ไม่มีใน list' },
  ],
  automotive: [
    { value: 'car_review',        label: 'รีวิวรถยนต์',                desc: 'ลองขับ ทดสอบ รีวิวรถใหม่' },
    { value: 'car_accessories',   label: 'อุปกรณ์ตกแต่งรถ',           desc: 'กล้องหน้ารถ ที่วางโทรศัพท์' },
    { value: 'car_care',          label: 'ดูแลรักษารถ / Car Care',     desc: 'ขัดเงา เคลือบ ดูแลสี' },
    { value: 'motorbike',         label: 'มอเตอร์ไซค์ / Motorbike',   desc: 'รีวิวรถ big bike สกู๊ตเตอร์' },
    { value: 'ev_car',            label: 'รถไฟฟ้า / EV',               desc: 'Tesla BYD MG ชาร์จ EV' },
    { value: 'automotive_other',  label: 'ยานยนต์อื่นๆ',              desc: 'ไม่มีใน list' },
  ],
  other: [
    { value: 'pet',        label: 'สัตว์เลี้ยง',                       desc: 'หมา แมว นก กระต่าย' },
    { value: 'diy_craft',  label: 'งานฝีมือ / DIY',                    desc: 'ทำของ ประดิษฐ์ handmade' },
    { value: 'gadget_tech', label: 'Gadget / Tech review',             desc: 'รีวิวมือถือ อุปกรณ์ tech' },
    { value: 'music',      label: 'ดนตรี / ร้องเพลง',                  desc: 'เล่นดนตรี cover ร้องเพลง' },
    { value: 'other_other', label: 'อื่นๆ ที่ไม่ใน list',              desc: 'บอกใน "ปัญหาหลัก"' },
  ],
}
